{
  "branches": ["master", "next"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github",
    [
        "@semantic-release/changelog",
        {
            "changelogFile": "CHANGELOG.md",
            "changelogTitle": "changelog"
        }
    ],
    "@semantic-release/npm",
    "@semantic-release/git"
  ]
}
