{
  "branches": ["master", "next"],
  "plugins": [
    "@semantic-release/git",
    [
        "@semantic-release/changelog",
        {
            "changelogFile": "CHANGELOG.md",
            "changelogTitle": "# changelog"
        }
    ]
  ]
}
