{ "branches": ["master", "next"], 
  "plugins": [
      "@semantic-release/commit-analyzer", #Default 1
      "@semantic-release/release-notes-generator", #Default 2
      [
        "@semantic-release/changelog",
        { "changelogFile": "CHANGELOG.md", "changelogTitle": "changelog" },
      ],
      # "@semantic-release/npm", #Default 3
      # "@semantic-release/github", #Default 4
      [
          "@semantic-release/github",
          {"assets": ["bin/*.gz","bin/*.zip"]}
      ],
      [
        "@google/semantic-release-replace-plugin",
        {
          "replacements": [
            {
              "files": ["version/version.go"],
              "from": "Version = \"*\"",
              "to": "Version = \"${nextRelease.version}\"",
              "results": [
                {
                  "file": "version/version.go",
                  "hasChanged": true,
                  "numMatches": 1,
                  "numReplacements": 1
                }
              ],
              "countMatches": true
            }
          ]
        }
      ],
      [ 
        "@semantic-release/git",
        {
          "assets": ["version/version.go","CHANGELOG.md"],
        }
      ],
      [
        "@semantic-release/exec", {
          "prepareCmd": "make releases VERSION=${nextRelease.version}"
        }
      ],
  ] 
}
