# This is a basic workflow that is manually triggered
name: auto publish release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'auto make'
        # Default value if no value is explicitly provided
        default: 'push'
        # Input has to be provided for the workflow to run
        required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  automake:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # <--- this

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic   # 您需要一个`id`来使用输出变量
        with:
          branch: master
          extra_plugins: |
            conventional-changelog/conventional-changelog-jshint
            @google/semantic-release-replace-plugin
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
