name: Aligner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go 1.14.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make releases

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic   # 您需要一个`id`来使用输出变量
        with:
          branch: master
          # semantic_version: 15.13.28
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}

